import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";

const Home: NextPage = () => {
  const [inputValue, setInputValue] = useState("");
  const [data, setData] = useState<string[] | null>(null);

  // TODO: Incomplete
  // const debounce = (func: Function, timeout: number = 500) => {
  //   let timer;
  //   return (...args: unknown[]) => {
  //     setTimeout(() => {
  //       func(args);
  //     }, timeout)
  //   }
  // }

  const fetchWords = async () => {
    const res = await fetch(`/api/search?term=${inputValue}`);
    const { words } = await res.json().catch((err) => console.error(err));

    setData(words);
  };

  useEffect(() => {
    fetchWords();
  }, [inputValue]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <input
          placeholder="Type to search"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
        />
        {data?.length ? (
          <ul>
            {data.map((word) => (
              <li key={word}>{word}</li>
            ))}
          </ul>
        ) : null}
      </main>
      <style jsx>{`
        main {
        }
      `}</style>
    </>
  );
};

export default Home;
